import sqlmodel
"""add week_day_number fiel to train

Revision ID: f3fe41c4d9ea
Revises: 1bc4273e43ec
Create Date: 2024-10-27 20:46:22.820294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fe41c4d9ea'
down_revision: Union[str, None] = '1bc4273e43ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train', sa.Column('week_day_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('train', 'week_day_number')
    # ### end Alembic commands ###
