import sqlmodel
"""init migration

Revision ID: a3ebd689bf31
Revises: 3cc16a93748f
Create Date: 2024-10-30 12:55:25.251811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ebd689bf31'
down_revision: Union[str, None] = '3cc16a93748f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
